// This file is auto-generated by config.firebase.cjs.
// Do not edit this file manually.

export const config = {
	production: false,
	label: "LOCAL",
	name: "@santashop/admin",
	version: "2026.08.0-alpha.1",
	appCheckKey: "2839440c-0a91-4c48-921a-451020157001",
	appCheckEnabled: false,
	programYear: 2026,
	shopDays: [12,13,15,16],
	emulatorPorts: {
		auth: 9099,
		functions: 5001,
		firestore: 8080,
		storage: 9199,
	},
};
