// This file is auto-generated by config.firebase.cjs.
// Do not edit this file manually.

export const config = {
	production: true,
	label: "TEST/QA",
	name: "@santashop/admin",
	version: "2025.2.1",
	appCheckKey: "6LfQqwkpAAAAAHyIhwZ4v9ZGl6lMdwzsh_maGnSU",
	appCheckEnabled: true,
};
