[tools]
node = "24"
pnpm = "latest"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]

[tasks.pnpm-install]
description = "Installs dependencies with pnpm"
run = "pnpm install"
sources = ["package.json", "pnpm-lock.yaml", "mise.toml"]
outputs = ["node_modules/.pnpm/lock.yaml"]
