// This file is auto-generated by config.firebase.cjs.
// Do not edit this file manually.

export const config = {
	production: false,
	label: "LOCAL",
	name: "@santashop/app",
	version: "2025.2.1",
	appCheckKey: "2839440c-0a91-4c48-921a-451020157001",
	appCheckEnabled: false,
};
