// This file is auto-generated by config.firebase.cjs.
// Do not edit this file manually.

export const config = {
	production: true,
	label: "PROD",
	name: "@santashop/app",
	version: "2025.2.1",
	appCheckKey: "6Lc4vgkpAAAAACOIJc4lTNn4wLzvuJkoz17t_RXH",
	appCheckEnabled: true,
	programYear: 2026,
	shopDays: [12,13,15,16],
	emulatorPorts: {
		auth: 9099,
		functions: 5001,
		firestore: 8080,
		storage: 9199,
	},
};
